name: AKIŞ APK Oluştur

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install
    
    # Yeni Eklenen Adım: Dosyaları Capacitor'un istediği formata sokar
    - name: Web Klasörünü Hazırla
      run: |
        mkdir www
        cp index.html www/
        sed -i 's/"webDir": "."/"webDir": "www"/g' capacitor.config.json
        
    - run: |
        npx cap add android
        npx cap sync android
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: AKIS-TV-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
